# Generated by Django 5.1.7 on 2025-04-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available_quantity', models.IntegerField(verbose_name=4)),
                ('product_desc', models.CharField(max_length=255)),
                ('product_image', models.ImageField(default='screen', upload_to='product_img')),
            ],
        ),
    ]
