# Generated by Django 5.1.7 on 2025-04-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_img/backimg.jpg', upload_to='product_img'),
        ),
    ]
