# Generated by Django 5.1.7 on 2025-04-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Cart',
            new_name='cart',
        ),
    ]
