# Generated by Django 5.1.7 on 2025-04-25 06:17

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartmentAddress',
            field=models.CharField(default='NP', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='NP', max_length=2),
        ),
    ]
