# Generated by Django 5.1.7 on 2025-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_userprofile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(verbose_name='Available Quantity'),
        ),
    ]
