# Generated by Django 5.1.7 on 2025-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_order_order_status_alter_product_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
