# Generated by Django 5.1.7 on 2025-05-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='product_price',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product_name',
        ),
    ]
