# Generated by Django 5.1.7 on 2025-05-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_orderitems_price_orderitems_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='apartmentAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='streetAddress',
        ),
    ]
