# Generated by Django 5.1.7 on 2025-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='walletid',
            field=models.CharField(default='552555555555', max_length=80),
        ),
    ]
