# Generated by Django 5.1.7 on 2025-05-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_payment_walletid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='ammount',
        ),
    ]
